FROM python:3.10-bookworm

WORKDIR /app

ENV PYTHONPATH=/app:$PYTHONPATH

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl

RUN pip install --upgrade pip

RUN mkdir -p /app/backend
COPY backend/requirements.txt /app/backend/

# --- Install Python dependencies ---
# SOLO INSTALA DESDE requirements.txt
RUN pip install --no-cache-dir -r /app/backend/requirements.txt

# Si 'es_core_news_sm' no está en requirements.txt o necesitas asegurarte de su descarga
# RUN python -m spacy download es_core_news_sm
# Descargar el modelo de spaCy
RUN python -m spacy download es_core_news_lg

# Install Tesseract OCR and language packs
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    tesseract-ocr \
    tesseract-ocr-spa \
    tesseract-ocr-eng \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY backend/ /app/backend/

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "backend.app:app"]